# Generated by Django 4.2 on 2023-05-08 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('rank', models.CharField(max_length=200, null=True)),
                ('availibity', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('marital_status', models.CharField(max_length=200, null=True)),
                ('date_birth', models.CharField(max_length=200, null=True)),
                ('birth_place', models.CharField(max_length=200, null=True)),
                ('worked_with_us', models.CharField(max_length=200, null=True)),
                ('vessel_type', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('zone', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('boiler_suit_size', models.CharField(max_length=200, null=True)),
                ('safety_shoe_size', models.CharField(max_length=200, null=True)),
                ('height', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('license_country', models.CharField(max_length=200, null=True)),
                ('INDoS_Number', models.CharField(max_length=200, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('permanent_address', models.CharField(max_length=200, null=True)),
                ('permanent_city', models.CharField(max_length=200, null=True)),
                ('permanent_state', models.CharField(max_length=200, null=True)),
                ('permanent_pincode', models.CharField(max_length=200, null=True)),
                ('temp_address', models.CharField(max_length=200, null=True)),
                ('temp_city', models.CharField(max_length=200, null=True)),
                ('temp_state', models.CharField(max_length=200, null=True)),
                ('temp_pincode', models.CharField(max_length=200, null=True)),
                ('mobile1', models.CharField(max_length=200, null=True)),
                ('mobile2', models.CharField(max_length=200, null=True)),
                ('landline', models.CharField(max_length=200, null=True)),
                ('email1', models.CharField(max_length=200, null=True)),
                ('email2', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('contact_person', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('management', models.CharField(choices=[('Owners', 'Owners'), ('Managers', 'Managers')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=200, null=True)),
                ('hide_expiry_date', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200, null=True)),
                ('doctor_name', models.CharField(max_length=200, null=True)),
                ('hospital_address', models.CharField(max_length=200, null=True)),
                ('hospital_city', models.CharField(max_length=200, null=True)),
                ('hospital_state', models.CharField(max_length=200, null=True)),
                ('hospital_phone', models.CharField(max_length=200, null=True)),
                ('hospital_email', models.CharField(max_length=200, null=True)),
                ('hospital_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, null=True)),
                ('document_file', models.FileField(null=True, upload_to='officedoc')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_agent', models.CharField(max_length=200, null=True)),
                ('port_contact_person', models.CharField(max_length=200, null=True)),
                ('port_agent_address', models.CharField(max_length=200, null=True)),
                ('port_agent_phone', models.CharField(max_length=200, null=True)),
                ('port_agent_email', models.CharField(max_length=200, null=True)),
                ('port_agent_city', models.CharField(max_length=200, null=True)),
                ('port_agent_state', models.CharField(max_length=200, null=True)),
                ('port_agent_country', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=200, null=True)),
                ('rank_order', models.CharField(max_length=200, null=True)),
                ('rank_category', models.CharField(choices=[('Officer', 'Officer'), ('Rating', 'Rating'), ('IV Crew', 'IV Crew')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200, null=True)),
                ('vendor_address', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VslType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsl_name', models.CharField(max_length=200, null=True)),
                ('vsl_type', models.CharField(max_length=200, null=True)),
                ('vsl_company', models.CharField(max_length=200, null=True)),
                ('IMO_Number', models.CharField(max_length=200, null=True)),
                ('vsl_flag', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user_image', models.ImageField(null=True, upload_to='userprofile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
