# Generated by Django 4.2 on 2023-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='import_files')),
            ],
        ),
    ]
