# Generated by Django 4.2 on 2023-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0002_excelfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
