# Generated by Django 4.2 on 2023-05-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0003_alter_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='management',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Managers', 'Managers')], max_length=200),
        ),
    ]
