# Generated by Django 4.2 on 2023-05-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0008_alter_hospital_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
