# Generated by Django 4.2 on 2023-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0011_rename_hospital_namee_hospital_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryname',
            name='country_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countryname',
            name='country_phone_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
